name: Doppler Secrets Upload
description: Upload a .env file to your Doppler project
branding:
  icon: arrow-up-circle
  color: purple
inputs:
  project:
    description: Project name
    required: true
  token:
    description: Doppler token
    required: true
  config_name:
    description: Configuration name to point the upload to (dev, stg, prd ...)
    required: false
    default: dev
  env_file:
    description: The path to your env file
    required: false
    default: .env

runs:
  using: composite
  steps:
    - uses: dopplerhq/cli-action@v1
    - name: Upload env file to Doppler
      shell: bash
      run: doppler secrets upload ${{ inputs.env_file }} --project ${{ inputs.project }} --config ${{ inputs.config_name }} --token ${{ inputs.token }}
